# Generated by Django 3.0.8 on 2020-07-14 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footBallApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchScheduling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('match_status', models.PositiveSmallIntegerField(choices=[(1, 'upcoming'), (2, 'inprogress'), (3, 'completed')], default=1)),
                ('result', models.CharField(blank=True, max_length=200, null=True)),
                ('first_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='footBallApp.Teams')),
                ('second_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='footBallApp.Teams')),
            ],
        ),
    ]
