# Generated by Django 3.0.8 on 2020-07-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footBallApp', '0002_matchscheduling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='team_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
